import puppeteer from 'puppeteer'
const browser = await puppeteer.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH, args: ['--no-sandbox'] })
const page = await browser.newPage()
await page.setViewport({ width: 1440, height: 900 })
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
await page.goto('http://127.0.0.1:4173/services', { waitUntil: 'networkidle0' })
if (!await page.$('.halcyon-services-workspace')) throw new Error('Services workspace did not render')
await page.evaluate(() => document.querySelectorAll('.service-compare-check')[0].click())
await page.evaluate(() => document.querySelectorAll('.service-compare-check')[1].click())
await new Promise((resolve) => setTimeout(resolve, 100))
if (!await page.$('.service-comparison')) throw new Error('Service comparison did not open')
await page.goto('http://127.0.0.1:4173/contact', { waitUntil: 'networkidle0' })
if (!await page.$('.enquiry-page-form')) throw new Error('Public contact page was gated or missing')
await page.goto('http://127.0.0.1:4173/portal', { waitUntil: 'networkidle0' })
if (!page.url().includes('/login')) throw new Error('Portal was not protected')
await page.evaluate(() => localStorage.setItem('virexo-marketplace-session', JSON.stringify({ name: 'QA User', email: 'demo@virexo.com' })))
await page.goto('http://127.0.0.1:4173/portal', { waitUntil: 'networkidle0' })
if (!await page.$('.portal-pro-shell')) throw new Error('Portal did not render')
if (errors.length) throw new Error(`Page errors: ${errors.join('; ')}`)
console.log('premium smoke: passed')
await browser.close()
